### ISSUE TITLE
Risk Targeting Coefficient Documentation

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-design-ws#101]
Create documentation for risk targeting coefficient endpoint.

- Add link to documentation fro main page
  - Near "deterministic" link
- Mimic format used for other end points.

Submit to @nluco-usgs for verbiage/naming standards review. Include PDF of rendered page as well as link to source code for edits.

**Comment by ehunter-usgs** [comment]
waiting for feedback from nico
