### ISSUE TITLE
Create T_L database loader scripts

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-design-ws#157]
- place gzipped csv on ftp server with other data files (based on T_L sql file provided by Eric)

- create schema
  - model after other data sets with "documents" and "regions"
- create loading script

(for local dev, need postgis for spatial column...)

**Comment by emartinez-usgs** [comment]
- Need to add document references for ASCE7-16 as well as ASCE41-13 to tsubl "documents.json"

**Comment by emartinez-usgs** [comment]
#194 addresses issues in this ticket, but has not yet been merged because other problems. this will auto-close when that pr is merged.
