### ISSUE TITLE
Document local database dev setup

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-design-ws#158]
- using docker containers
- possibly in README getting started?
- postgis is needed for new T_L dataset

**Comment by emartinez-usgs** [comment]
- Need to include line item for how to load TsubL data (similar to prob/det/risk datasets).
- Possibly update to simple state to run three commands:
```
node src/lib/db/deterministic/load_deterministic.js
node src/lib/db/probabilistic/load_probabilistic.js
node src/lib/db/risk_coefficient/load_risk_coefficient.js
node src/lib/db/tsubl/load_tsubl.js
```
