### ISSUE TITLE
Add T_L to ASCE 41-13 factory and output

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-design-ws#162]

**Comment by emartinez-usgs** [comment]
Looks mostly good.

- Needs rebase.
- Address codacy issues. (https://www.codacy.com/app/usgs/earthquake-design-ws/pullRequest?prid=884619)
- Address comments in review (on pull request #186).

**Comment by emartinez-usgs** [comment]
Still some issues with #194. Probably could further simplify how/when TL is computed.

**Comment by emartinez-usgs** [comment]
Merged PR in the interest of moving forward as things are technically working. Still need some work on this issue however:

- Example on documentation (HTML) page shows t-sub-l in incorrect location.
- Documentation (HTML) for "Custom" hazard level should not indicate that it includes TL data.
- TL data should be included in the result returned by the factory. The handler should not try to directly access TL data from a member property on the factory itself.
- Codacy test is reporting a minor problem.
