### ISSUE TITLE
Put 2014 data files on ftp

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-design-ws#163]
- Eric will provide link/instructions to access data files.
- All data (probabilistic, deterministic, and risk coefficients) in same file.
- Transform into separate files for each type, following conventions of other files
- update to ftp

**Comment by emartinez-usgs** [comment]
Raw data files here: ftp://hazards.cr.usgs.gov/emartinez/nshmp-2014.tgz

**Comment by ehunter-usgs** [comment]
I'm splitting the raw file into its component parts.

**Comment by ehunter-usgs** [comment]
Files (E2014*.csv.gz) can be found on the FTP server:
ftp://hazards.cr.usgs.gov/web/earthquake-design-ws/

This will also be reviewable once  #164 is finished.

**Comment by ehunter-usgs** [comment]
This has been updated, it turns out the only region that was updated with the 2014 data was COUS, the 2012 GNMI and 2012 AMSAM data was already loaded to the FTP

**Comment by emartinez-usgs** [comment]
What is the AK0P10 data set? I believe we only use/load AK0P05 ... ? Can we remove unused datasets to avoid future confusion?

**Comment by ehunter-usgs** [comment]
@emartinez-usgs I changed the name to `AK0P05*` we had the wrong grid spacing labeling for the filename. I also removed the outdated files, but for some reason they are not updating on the FTP site?

**Comment by ehunter-usgs** [comment]
I ran a deleting rsync against the old data, things should be in sync now.
