### ISSUE TITLE
Update existing data loaders with 2014 data files

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-design-ws#164]
- Eric will provide metadata mapping
- document metadata parameters are in files provided by Eric
ss and s1 direction factors are like 1.3 and 1.1
percentile factor is like 1.8
flooring factor is like 0.5 or 0.6
grid spacing is part of data (check data files)

asce 7-16 uses a different floor than nehrp 2015, but data is from nehrp 2015; may not be same as what's hardcoded in data files... use what's hardcoded in source files if there are conflicts.  @nluco-usgs has all the answers.

**Comment by jmfee-usgs** [comment]
- Add data files to regions.json
- Add document metadata and region mapping to documents.json

For now, use ASCE7-16 as document

**Comment by emartinez-usgs** [comment]
- ASCE7-16 `model_version` in documents.json should be `4.0.x`
