### ISSUE TITLE
Clean up tests

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-design-ws#190]
Currently several tests print a warning about unhandled promise rejections. Probably should take care of this (within the source, not the tests itself).

```
UnhandledPromiseRejectionWarning: Unhandled promise rejection
```

Review output from `npm run test` to see these errors.

**Comment by jdbrown-USGS** [comment]
Project archived issue can be found here https://code.usgs.gov/ghsc/hazdev/earthquake-design-ws/issues/190
