### ISSUE TITLE
Spectra TL Support

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-design-ws#212]
Update spectra calculator to extend to (beyond?) TL value.

Note, the spectra formula changes at T>=TL (formula documented in code comments already).

Question for @nluco-usgs :: How far should we extend the tail of the spectra? Tmax = 1.5*TL ? Currently we have Tmax hard-coded at T=2.0 s. Since TL may be as large as 12, this needs to be adjusted. Should there be a hard cap Tmax anymore?

**Comment by nluco-usgs** [comment]
How about Tmax = TL+1, just to show the change in the formula? Note: TL can be as large as 16. Should we adjust the increments of T? What are the increments now?

**Comment by emartinez-usgs** [comment]
The current increment is 0.05. Once we get around to implementing this we can see how different increments affect the overall shape. Suggestions are welcome.
