### ISSUE TITLE
Refactor update spectra-factory with vertical component calc

### ISSUE THREAD

**Issue by jdbrown-USGS** [usgs/earthquake-design-ws#237]
- get x values
  - first x value = 0
  - last x value ( t_l + 1 ) 
  - other x values should increment by 0.05 but also include 0.025, 0.05, 0.15, 2.0, t_l, (0.2 * ts), ts
 
```
if (gm1 > gms) {
  gms = gm1;
}
ts = gm1 / gms;
```

- add getHorizontalValue
  - implement existing get spectrum piece-wise logic

- add get vertical value method
  - implement piece-wise logic from 11.9.2

    > ![screen shot 2017-09-11 at 2 51 17 pm](https://user-images.githubusercontent.com/1932750/30296853-da130166-9702-11e7-8b44-b68810d373c2.png)

- getHorizontalSpectrum
  - gets x values and calls getHorizontalValue for each x value to get corresponding y value

- getVerticalSpectrum
  - gets x values and calls getVerticalValue for each x value to get corresponding y value

**Comment by jdbrown-USGS** [comment]
- incorporates #212

**Comment by jcaple-devtech** [comment]
We chose not to refactor the individual value methods at this time thinking this may be more appropriate when a reference document requires a different horizontal or vertical spectrum calculation.
