### ISSUE TITLE
Correct deterministic data 

### ISSUE THREAD

**Issue by jdbrown-USGS** [usgs/earthquake-design-ws#258]
Mapped_pgad, mapped_s1d, and mapped_ssd values are 0 for the majority of locations.

**Comment by emartinez-usgs** [comment]
For all regions, when deterministic data = 0, set deterministic data as follows:

pgad = 0.005
s1d = 0.0025
ssd = 0.005

**Comment by emartinez-usgs** [comment]
Data are updated and available here: ftp://hazards.cr.usgs.gov/web/earthquake-design-ws/

Should include update timestamp of Sep 26, 2017.

**Comment by jcaple-devtech** [comment]
I confirm that update Deterministic Data Files are on the ftp server.

Can you confirm that your data changes apply only to Region IDs 5 and 7?
