### ISSUE TITLE
empty asce7-05 sdcs and sdc1 values 

### ISSUE THREAD

**Issue by jmfee-usgs** [usgs/earthquake-design-ws#266]
`sdcs`,
`sdc1`

/ws/designmaps/asce7-05.json?latitude=34&longitude=-118&riskCategory=III&siteClass=C&title=Example
<img width="350" alt="screen shot 2017-09-21 at 3 12 34 pm" src="https://user-images.githubusercontent.com/1717896/30719052-564424ca-9edf-11e7-8388-cb3c5b2ed5f3.png">

**Comment by jdbrown-USGS** [comment]
@nluco-usgs 
sdcs and sdc1 should be empty strings for this location. 
https://github.com/usgs/earthquake-design-ws/blob/63f1f5e4ec5ec6c32123f3dd830a77e8b86bb58a/src/lib/design-category-factory.js#L115

Is this correct?

**Comment by emartinez-usgs** [comment]
This appears to be the intended behavior. Other locations (with lower S1 values) return SDCS and SDC1 as expected.
