### ISSUE TITLE
Legacy Factory

### ISSUE THREAD

**Issue by jdbrown-USGS** [usgs/earthquake-design-ws#3]
- Up-convert old data set to new data set. see doc

**Comment by jdbrown-USGS** [comment]
- getLegacyData
  - Cache promise  with corresponding input 
  - accept new params
  - translate to legacy params
  - make legacy web service request
  - perform bi linear spatial interpolation 
  - resolve promise with interpolated data

**Comment by emartinez-usgs** [comment]
- Add promise caching per unique request
- Clean up tests
  - Use one `describe` per method on the factory
  - Ensure the stated description (first parameter to `it` method) matches what is actually being tested.
- Promise from `getLegacyData` method must at least include data and metadata. It is simplest to return the full response but with interpolated data.

**Comment by emartinez-usgs** [comment]
- Constructor sets variable `_this.path`, but when building options for a request, the code is looking for `_this.pathname`. Should use the same variable in both places.
- If no port number is explicitly set in the URL, port comes back as null. Some attempt should be made to look at the protocol and infer a port in this case, `http:` --> 80 `https:` --> 443.
- Input parameters need to be mapped back to legacy values. For example, in the new API, `referenceDocument` is a string like "ASCE7-16", but in the legacy API, `design_code_id` is an integer.
