### ISSUE TITLE
Refactor Similar Code

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-design-ws#304]
Several factories/handlers are running almost identical code. Refactor this code to a common abstraction layer as much as possible.

Consider...
- ... based on NSHM 2014
   - NEHRP 2015
   - ASCE7-16
- ... based on NSHM 2008
   - NEHRP 2009
   - ASCE7-10
   - IBC 2012
   - IBC 2015
- ... based on NSHM 2002
   - NEHRP 2003
   - ASCE7-05
   - IBC 06/09

- ASCE41
   - -13 vs -17

**Comment by emartinez-usgs** [comment]
Some suggestions...

- ASCE41Handler as a print statement on line 160. This should be removed.
- Maybe create a generic "Handler" class that implements the basic API (checkParams, formatResult, get). Have other handlers extend this.
- Maybe a DBHandler to extend base Hander and then serve as a basis to t-sub-l-data-handler and gridded-data-handler.
  - Implement createDbPool method.

If these seem overly involved, please enter a new issue for them and feel free to close this.

**Comment by jdbrown-USGS** [comment]
Project archived issue can be found here https://code.usgs.gov/ghsc/hazdev/earthquake-design-ws/issues/304
