### ISSUE TITLE
Modify existing DEV Jenkins Project

### ISSUE THREAD

**Issue by jcaple-devtech** [usgs/earthquake-design-ws#306]
1) Build App Images
2) Run App Image in Container 
3) Test App in Container
4) Tear down Dev Container
5) Deploy Image to Dev Registry
6) Start new Dev App Container from Image in Registry

**Comment by emartinez-usgs** [comment]
- Currently deploy to dev using new pipeline.
- Does not do ZAP PEN testing.
- New deploys leverage data in a container
- Currently using internal image registry
- Currently using docker-compose.yml v2
