### ISSUE TITLE
Implement Router

### ISSUE THREAD

**Issue by jcaple-devtech** [usgs/earthquake-design-ws#314]

**Comment by emartinez-usgs** [comment]
Consider using NGINX

Router should...
- Listen on a public port
- Support a custom "routing table" 
- Route requests to URLs based on incoming request paths
- Support dynamically loading a new routing table configuration without restarting system

**Comment by jcaple-devtech** [comment]
Router integration with CI/CD Pipeline is working.  This functionality will be demonstrated.
