### ISSUE TITLE
Implement Deploy Pipeline Phase 0

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-design-ws#319]
Finish work on deploy pipeline for phase 0.
- Docker needs to be updated and disk expansion needs to be completed (IT pre-req).

Deploy stack should include:
- 1 application replica
- 1 database replica

Deployment does not need to be zero-downtime yet.

**Comment by jcaple-devtech** [comment]
GitLab Merge Request Submitted

**Comment by emartinez-usgs** [comment]
Merged. Stacks appear to be running on dev.
