### ISSUE TITLE
Document Steps to Prepare Deploy Targets for CI/CD

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-design-ws#320]
- Do this while setting up development build/deploy pipelines.
- Consider building into Puppet

**Comment by jcaple-devtech** [comment]
* Add jenkins-deploy to docker and hazdev group
* Add jenkins-deploy ssh key to target server
* perform a docker swarm init on target server
* Create data directory for container and postgres container mount volume
  -- mkdir -p /var/www/data
  -- chown hazdev:hazdev /var/www/data
  -- chmod -R 775 /var/www/data
  -- chmod -R g+s /var/www/data
    --- These may all need sudo
* Router configuration steps

**Comment by jcaple-devtech** [comment]
I added some additional notes to the document Jeremy started:

https://docs.google.com/document/d/12ek5dKg9y0aQefDbyfA_9GMaNImfNqBETJqiWcY1XbA/edit?ts=599f53d2#
