### ISSUE TITLE
Reconsider blank sdcs and sdc1 response when s1>=0.75

### ISSUE THREAD

**Issue by nluco-usgs** [usgs/earthquake-design-ws#340]
Is there a less confusing (to the user) alternative to this code snippet? ...

        } else if (['I', 'II', 'III'].indexOf(riskCategory) !== -1 &&
            s1 >= 0.75) {
          sdsCategory = '';
          sd1Category = '';

          sdCategory = 'E';
        } else if (riskCategory === 'IV' && s1 >= 0.75) {
          sdsCategory = '';
          sd1Category = '';

          sdCategory = 'F';

@emartinez-usgs

**Comment by jdbrown-USGS** [comment]
Project archived issue can be found here https://code.usgs.gov/ghsc/hazdev/earthquake-design-ws/issues/340
