### ISSUE TITLE
Binary Search Library

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-design-ws#364]
Swap out "binarysearch" to be "binary-search" instead. The latter package is more active and has a larger user base.

Update the usage to reflect the slightly different API.

Update design-category-factory method `mapDesignCategory` to use binary search instead of loop.

**Comment by jdbrown-USGS** [comment]
Project archived issue can be found here https://code.usgs.gov/ghsc/hazdev/earthquake-design-ws/issues/364
