### ISSUE TITLE
AASHTO Calculate Design Category 

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-design-ws#365]
Move `calculateDesignCategory` to separate class. Possibly as new method on existing design-category-factory, or possibly as new (sub-) class for calculating AASHTO specific design categories.

Write unit tests to test this method.

**Comment by jdbrown-USGS** [comment]
Project archived issue can be found here https://code.usgs.gov/ghsc/hazdev/earthquake-design-ws/issues/365
