### ISSUE TITLE
AASHTO Remove computeSpectralAcceleration

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-design-ws#370]
This method is redundant with `computeSiteModifiedValue`. Alternatively, overload `computeDesignValue` method inherited from `NSHMFactory` to not apply the 2/3 factor and instead return the provided input value.

**Comment by jdbrown-USGS** [comment]
Project archived issue can be found here https://code.usgs.gov/ghsc/hazdev/earthquake-design-ws/issues/370
