### ISSUE TITLE
AASHTO Method Documentation

### ISSUE THREAD

**Issue by emartinez-usgs** [usgs/earthquake-design-ws#374]
Correct documentation for `computeBasicDesign` in the `aashto_2009-factory` class. Notably:

- `data` is an object, not an array
- `metadata` is not used, no need to mention it
- `pga` is also included on the returned promise resolution

**Comment by jdbrown-USGS** [comment]
Project has been archived issue can be found here https://code.usgs.gov/ghsc/hazdev/earthquake-design-ws/issues/374
