### ISSUE TITLE
In responses, consider changing order of ...

### ISSUE THREAD

**Issue by nluco-usgs** [usgs/earthquake-design-ws#377]
... ssrt, crs, ssuh to ssrt, ssuh, crs; and s1rt, cr1, s1uh to s1rt, s1uh, cr1; since cr is merely the rt/uh ratio.

**Comment by jdbrown-USGS** [comment]
Project has been archived issue can be found here https://code.usgs.gov/ghsc/hazdev/earthquake-design-ws/issues/377
